apiVersion: v1
kind: Service
metadata:
  name: ecommercewebserver-service
  labels:
    run: ecommerceweb-service
spec:
  type: NodePort 
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: ecommerce 
